import type { Chatter, Model, Profile, ShiftWithChatter } from './types';
import { getWeekDates } from './utils';

const now = new Date().toISOString();
const weekDates = getWeekDates(0);

export const previewAdminProfile: Profile = {
  id: 'preview-admin',
  email: 'preview@shiftpro.local',
  display_name: 'תצוגת מנהל',
  role: 'admin',
  created_at: now,
};

export const previewChatterProfile: Profile = {
  id: 'preview-chatter-user',
  email: 'chatter@shiftpro.local',
  display_name: 'נועה כהן',
  role: 'chatter',
  created_at: now,
};

export const previewChatters: Chatter[] = [
  {
    id: 'chatter-noa',
    name: 'נועה כהן',
    phone: '0500000001',
    token: 'preview-noa',
    active: true,
    last_sign_in_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'chatter-daniel',
    name: 'דניאל לוי',
    phone: '0500000002',
    token: 'preview-daniel',
    active: true,
    last_sign_in_at: null,
    created_at: now,
    updated_at: now,
  },
];

export const previewModels: Model[] = [
  { id: 'model-lina', name: 'Lina', active: true, created_at: now },
  { id: 'model-maya', name: 'Maya', active: true, created_at: now },
  { id: 'model-aria', name: 'Aria', active: true, created_at: now },
];

export const previewShifts: ShiftWithChatter[] = [
  {
    id: 'preview-shift-merged',
    chatter_id: 'chatter-noa',
    date: weekDates[1],
    start_time: '12:00:00',
    end_time: '19:00:00',
    model: 'Lina',
    model_id: 'model-lina',
    platform: 'telegram',
    status: 'scheduled',
    clocked_in: null,
    clocked_out: null,
    created_at: now,
    updated_at: now,
    chatters: { name: 'נועה כהן', phone: '0500000001' },
    shift_assignments: [
      {
        id: 'assignment-lina-tg',
        shift_id: 'preview-shift-merged',
        model_id: 'model-lina',
        model: 'Lina',
        platform: 'telegram',
        shift_date: weekDates[1],
        shift_start_time: '12:00:00',
        assigned_at: now,
      },
      {
        id: 'assignment-lina-of',
        shift_id: 'preview-shift-merged',
        model_id: 'model-lina',
        model: 'Lina',
        platform: 'onlyfans',
        shift_date: weekDates[1],
        shift_start_time: '12:00:00',
        assigned_at: now,
      },
      {
        id: 'assignment-maya-tg',
        shift_id: 'preview-shift-merged',
        model_id: 'model-maya',
        model: 'Maya',
        platform: 'telegram',
        shift_date: weekDates[1],
        shift_start_time: '12:00:00',
        assigned_at: now,
      },
    ],
  },
  {
    id: 'preview-shift-noa-completed',
    chatter_id: 'chatter-noa',
    date: weekDates[0],
    start_time: '12:00:00',
    end_time: '19:00:00',
    model: 'Maya',
    model_id: 'model-maya',
    platform: 'telegram',
    status: 'completed',
    clocked_in: `${weekDates[0]}T12:01:00.000Z`,
    clocked_out: `${weekDates[0]}T19:00:00.000Z`,
    created_at: now,
    updated_at: now,
    chatters: { name: 'נועה כהן', phone: '0500000001' },
    shift_assignments: [
      {
        id: 'assignment-noa-maya-tg',
        shift_id: 'preview-shift-noa-completed',
        model_id: 'model-maya',
        model: 'Maya',
        platform: 'telegram',
        shift_date: weekDates[0],
        shift_start_time: '12:00:00',
        assigned_at: now,
      },
    ],
  },
  {
    id: 'preview-shift-next',
    chatter_id: 'chatter-noa',
    date: weekDates[5],
    start_time: '12:00:00',
    end_time: '19:00:00',
    model: 'Lina',
    model_id: 'model-lina',
    platform: 'telegram',
    status: 'scheduled',
    clocked_in: null,
    clocked_out: null,
    created_at: now,
    updated_at: now,
    chatters: { name: 'נועה כהן', phone: '0500000001' },
    shift_assignments: [
      {
        id: 'assignment-next-lina-tg',
        shift_id: 'preview-shift-next',
        model_id: 'model-lina',
        model: 'Lina',
        platform: 'telegram',
        shift_date: weekDates[5],
        shift_start_time: '12:00:00',
        assigned_at: now,
      },
      {
        id: 'assignment-next-lina-of',
        shift_id: 'preview-shift-next',
        model_id: 'model-lina',
        model: 'Lina',
        platform: 'onlyfans',
        shift_date: weekDates[5],
        shift_start_time: '12:00:00',
        assigned_at: now,
      },
    ],
  },
  {
    id: 'preview-shift-pending',
    chatter_id: 'chatter-daniel',
    date: weekDates[2],
    start_time: '19:00:00',
    end_time: '02:00:00',
    model: null,
    model_id: null,
    platform: null,
    status: 'pending',
    clocked_in: null,
    clocked_out: null,
    created_at: now,
    updated_at: now,
    chatters: { name: 'דניאל לוי', phone: '0500000002' },
    shift_assignments: [],
  },
  {
    id: 'preview-shift-active',
    chatter_id: 'chatter-noa',
    date: weekDates[3],
    start_time: '19:00:00',
    end_time: '02:00:00',
    model: 'Aria',
    model_id: 'model-aria',
    platform: 'onlyfans',
    status: 'active',
    clocked_in: `${weekDates[3]}T19:04:00.000Z`,
    clocked_out: null,
    created_at: now,
    updated_at: now,
    chatters: { name: 'נועה כהן', phone: '0500000001' },
    shift_assignments: [
      {
        id: 'assignment-aria-of',
        shift_id: 'preview-shift-active',
        model_id: 'model-aria',
        model: 'Aria',
        platform: 'onlyfans',
        shift_date: weekDates[3],
        shift_start_time: '19:00:00',
        assigned_at: now,
      },
    ],
  },
  {
    id: 'preview-shift-completed',
    chatter_id: 'chatter-daniel',
    date: weekDates[4],
    start_time: '12:00:00',
    end_time: '19:00:00',
    model: 'Maya',
    model_id: 'model-maya',
    platform: 'onlyfans',
    status: 'completed',
    clocked_in: `${weekDates[4]}T12:00:00.000Z`,
    clocked_out: `${weekDates[4]}T19:02:00.000Z`,
    created_at: now,
    updated_at: now,
    chatters: { name: 'דניאל לוי', phone: '0500000002' },
    shift_assignments: [
      {
        id: 'assignment-maya-of',
        shift_id: 'preview-shift-completed',
        model_id: 'model-maya',
        model: 'Maya',
        platform: 'onlyfans',
        shift_date: weekDates[4],
        shift_start_time: '12:00:00',
        assigned_at: now,
      },
    ],
  },
];
