import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase';
import type { Chatter } from '../lib/types';

interface UseChattersReturn {
  chatters: Chatter[];
  loading: boolean;
  fetchChatters: () => Promise<void>;
  createChatter: (name: string, phone: string) => Promise<{ error: string | null }>;
  updateChatter: (id: string, data: Partial<Chatter>) => Promise<{ error: string | null }>;
  deleteChatter: (id: string) => Promise<{ error: string | null }>;
  toggleActive: (id: string, active: boolean) => Promise<{ error: string | null }>;
}

export function useChatters(): UseChattersReturn {
  const [chatters, setChatters] = useState<Chatter[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchChatters = useCallback(async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('chatters')
      .select('*')
      .order('name', { ascending: true });

    if (!error && data) {
      setChatters(data as Chatter[]);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    let active = true;
    Promise.resolve().then(() => {
      if (active) {
        void fetchChatters();
      }
    });
    return () => {
      active = false;
    };
  }, [fetchChatters]);

  const createChatter = useCallback(
    async (name: string, phone: string): Promise<{ error: string | null }> => {
      // token is auto-generated by the DB (default gen_random_uuid() or similar)
      const { data, error } = await supabase
        .from('chatters')
        .insert({ name, phone })
        .select()
        .single();

      if (!error && data) {
        setChatters(prev =>
          [...prev, data as Chatter].sort((a, b) => a.name.localeCompare(b.name))
        );
      }
      return { error: error?.message ?? null };
    },
    []
  );

  const updateChatter = useCallback(
    async (id: string, data: Partial<Chatter>): Promise<{ error: string | null }> => {
      const { data: updated, error } = await supabase
        .from('chatters')
        .update(data)
        .eq('id', id)
        .select()
        .single();

      if (!error && updated) {
        setChatters(prev =>
          prev
            .map(c => (c.id === id ? (updated as Chatter) : c))
            .sort((a, b) => a.name.localeCompare(b.name))
        );
      }
      return { error: error?.message ?? null };
    },
    []
  );

  const deleteChatter = useCallback(
    async (id: string): Promise<{ error: string | null }> => {
      const { error } = await supabase.from('chatters').delete().eq('id', id);
      if (!error) {
        setChatters(prev => prev.filter(c => c.id !== id));
      }
      return { error: error?.message ?? null };
    },
    []
  );

  const toggleActive = useCallback(
    async (id: string, active: boolean): Promise<{ error: string | null }> => {
      const { data: updated, error } = await supabase
        .from('chatters')
        .update({ active })
        .eq('id', id)
        .select()
        .single();

      if (!error && updated) {
        setChatters(prev =>
          prev.map(c => (c.id === id ? (updated as Chatter) : c))
        );
      }
      return { error: error?.message ?? null };
    },
    []
  );

  return {
    chatters,
    loading,
    fetchChatters,
    createChatter,
    updateChatter,
    deleteChatter,
    toggleActive,
  };
}
